### ISSUE TITLE
HTML Support

### ISSUE THREAD

**Issue by hakanozkaptan** [anteriovieira/vue-swal#3]
Hello, I am using the html: 'htmlCode <b>Bold</b>' parameter like this but its giving a blank.
how to use, html parameter.

Big regards

**Comment by anteriovieira** [comment]
Hi @hakanozkaptan try:

```js
this.$swal("Write something here:", {
  content: "input",
}).then(value => {
  this.$swal(`You typed: ${value}`)
})


```

[Example here (jsfiddle)](https://jsfiddle.net/anteriovieira/kp1kjdtj/)
