### ISSUE TITLE
access with Vue.$swal

### ISSUE THREAD

**Issue by empresarrollo** [anteriovieira/vue-swal#4]
is it possible to access with Vue.$swal instead of this.$swal ? I need Vue.$swal because I wanna use it outside a component, in an interceptor for axios.

**Comment by anteriovieira** [comment]
Hi @empresarrollo , yes you can do this.

The line below makes this possible.
https://github.com/anteriovieira/vue-swal/blob/c94bff409b71d5c05a38153748e016e7b3cc0af1/src/index.js#L4
